spring:
    # Profile
    application:
        name: SpringNaming
    # DataSource
    datasource:
        url: jdbc:mysql://localhost:3306/sn_data?serverTimezone=Asia/Taipei
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    # SessionFactory
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: validate
            naming:
                # physical-strategy ????????????????????????????????physical-strategy??????????????????????????????????
                physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
                # implicit-strategy ??????????????????????????????@Table?@Column????implicit-strategy?????????????????????implicit-strategy???????
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect